import { useState, useEffect } from "react";
import {
  AppShell,
  Header,
  MediaQuery,
  Burger,
  useMantineTheme,
  Container,
} from "@mantine/core";

import Head from "next/head";

import NavbarCore from "./NavbarCore";

import { GoogleButton } from "../social-buttons/GoogleButton";

import { useSession, signIn, signOut } from "next-auth/react";
import { MantineLogo } from "@mantine/ds";

// redux
import { useAppSelector } from "@/hooks/redux";
import { selectTitle } from "@/slice/title/titleSlice";

type DefaultLayoutProps = {
  children: React.ReactNode;
};

export default function DefaultLayout({ children }: DefaultLayoutProps) {
  const { data: session, status } = useSession();
  const title = useAppSelector(selectTitle);

  const theme = useMantineTheme();
  const [opened, setOpened] = useState(false);
  const [auth, setAuth] = useState(false);

  useEffect(() => {
    if (status === "authenticated") {
      setAuth(true);
    } else {
      setAuth(false);
    }
  }, [session, status]);

  return (
    <>
      <Head>
        <title>{title}</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <AppShell
        styles={{
          main: {
            background:
              theme.colorScheme === "dark"
                ? theme.colors.dark[8]
                : theme.colors.gray[0],
          },
        }}
        navbarOffsetBreakpoint="md"
        navbar={
          auth ? (
            <NavbarCore
              p="md"
              hiddenBreakpoint="md"
              hidden={!opened}
              width={{ sm: 300 }}
              logOut={() => signOut()}
              username={session?.user?.name || ""}
              email={session?.user?.email || ""}
              avatar={session?.user?.image || ""}
            />
          ) : (
            <></>
          )
        }
        header={
          <Header height={{ base: 70, md: 70 }} p="md">
            <Container size="xl">
              <div
                style={{
                  display: "flex",
                  justifyContent: "space-between",
                  alignItems: "center",
                  height: "100%",
                }}>
                <MediaQuery largerThan="md" styles={{ display: "none" }}>
                  <Burger
                    opened={opened}
                    onClick={() => setOpened((o) => !o)}
                    size="sm"
                    color={theme.colors.gray[6]}
                    mr="xl"
                  />
                </MediaQuery>
                <MediaQuery smallerThan="sm" styles={{ display: "none" }}>
                  <MantineLogo size={28} />
                </MediaQuery>
                {!auth ? (
                  <GoogleButton radius="xl" logIn={() => signIn()}>
                    Sign In Google
                  </GoogleButton>
                ) : (
                  <></>
                )}
              </div>
            </Container>
          </Header>
        }>
        {children}
      </AppShell>
    </>
  );
}
